### ISSUE TITLE
Incompatability with Librarian's Balance

### ISSUE THREAD

**Issue by Ynaught** [RamGemes/Tome-Reader#1] opened 2024-06-20 04:38 UTC
This mod also lets you place enchantment books on a lectern with rightclick. However, it also removes those books with the same button. So when both are installed at the same time, it triggers book place and triggers book remove on the same click.

I am not sure how you would fix this since you need to right click on the booked-lecturn to access the GUI, but doing so also causes the other mod to remove the book.

**Comment by mistrk7** [comment] 2024-06-21 17:07
Hi RamGames, I am the creator of [Librarian's Balance](https://modrinth.com/datapack/librarians-balance) which is a datapack that includes similar functionality.
Just want to say that I really like your mod and it would work well with my pack!

I'm trying to add compatibility with it. If you can I just need you to add a small thing.

There are enchanted books with a **minecraft:custom_data** component boolean of 'sealed'. 

![image](https://github.com/RamGemes/Tome-Reader/assets/66379077/149d811e-1bff-4f79-bc4a-1e61b4bb8d69)
Either give them a 'closed' look when on a lectern, or don't make them placeable on a lectern at all.

![image](https://github.com/RamGemes/Tome-Reader/assets/66379077/69e9e8f5-1101-4396-a2ba-32d2d868ff38)
This would be enabled based on this value in the world files (1=true). **yourworld/data/scoreboard.dat** 

![image](https://github.com/RamGemes/Tome-Reader/assets/66379077/db0637e5-4a7f-4980-a2d5-16cf49b8c1ec)

Then if you could do the same for the list of 'blacklisted books' too, then that would be all.

![image](https://github.com/RamGemes/Tome-Reader/assets/66379077/ecdecc28-d0db-44d9-ad2e-c0b138a93677)

Thanks.

I'm not a java modder but there's a mod-compiled version of my datapack on Modrinth. If you want, I could add the 'mixins' to this patch on to that so you don't have to ship them directly. I'm not exactly sure how that works though. could be completely wrong on that.

**Comment by Ynaught** [comment] 2024-06-21 19:22
> Either give them a 'closed' look when on a lectern, or don't make them placeable on a lectern at all.

Wouldn't this effect how the Tomb Reader mod works (stand alone-wise) in a potentially negative way if used in a world that doesn't include your datapack/mod @mistrk7?

Having the book opened is an esthetic choice and there are more cleaner solutions other than effecting the integrity/vision of a mods esthetics. I could be reading this wrong though and might be misunderstanding what your request would actually do. The issue presumable is due to an overlapped redundancy when both mods are installed together. Thus only one of you would have to add the option to remove that redundancy when a user enables the setting manually or if one of you makes it automatic based on detecting the presence of the other's mod.

**Comment by mistrk7** [comment] 2024-06-21 19:33
@Ynaught Probably not since the "sealed" custom data needs to be there on the item. So basically the closed book would only appear if the book item is specifically labelled by librarian's balance. It shouldn't affect the vanilla game in any way. I already have most of it working, it's just the 'sealed' variant exclusion needs to work on their end. And for the datapack to recognise the mod there could be a script that flips a value in my pack.

**Comment by Ramixin** [comment] 2024-06-21 20:43
Thank you @Ynaught for reporting this and @mistrk7 for working with me. Modifying/reading scoreboard values from a modding point of view can be very sketchy and may lead to some incompatibilities with other mods. What I can do is the following:
- Add a tag to render the book closed. This tag will take item component names / NBT names to check for
- Add a tag for blacklisted enchantments. This will take the identifiers (minecraft:enchantment_name) of each enchantment

Is this what would be needed?

**Comment by mistrk7** [comment] 2024-06-21 21:05
Thanks @RamGemes ! The tag to render the 'sealed' books closed should be good. However blacklisted enchantments are a player entered value so that wouldn't work. It's okay though. Those are optional, so you can leave blacklisted books how they are. 

Instead of flipping a value, would you be able to summon a tagged entity in the middle of the world for me to detect instead? This way i'll be able to kill it and automatically toggle the compatibility changes on my end. If you have any better ideas let me know.

**Comment by Ramixin** [comment] 2024-06-21 21:52
I'm glad the tag would work, but doing anything to make a mod detectable by data-packs will be inherently scuffed. I could maybe add an NBT tag to a lectern an enchanted book was placed on via Tome Reader. Other than that option, there is nothing I can do reliably.

**Comment by Ynaught** [comment] 2024-06-22 00:09
Woah, so we are doing a detecting system and cross-mod communications. . . heh, cool. Love seeing this kind of brainstorming. ^u^

Not to be an annoying know-nothing, but for the sake of the issue report, can one of you explain in technical terms why the bug actually happens? Ya know, for future readers just incase. I myself prefer hearing from those who know better than rather than working off my own presumptions on topics I'm not too well versed in, so the breakdown of the cause of the issue would be beneficial to me as well.


> I could maybe add an NBT tag to a lectern an enchanted book was placed on via Tome Reader.

This reminds me of a similar issue with a mod called Easy Magic. In easy magic, it gives the Enchanting Table custom properties, not unlike how you both give the lecterns custom properties. One issue the mod runs into is if an enchantment table is placed into the world before you install the mod, it would not work. Only enchanting tables that were either placed or generated after mod instillation would work. To get around this, the mod developer left a note on the mod page to break and re-place the enchanting table down. My guess is this is how they add the NBT data, assuming that's even what re-placing it even does.

**Comment by Ramixin** [comment] 2024-06-22 00:18
The issue is that Tome Reader injects itself into the event that checks whether a player is holding a viable item to put on a lectern and applies the book. Librarian's Balance does a different check later in the tick/next tick. This check sees there is a book on the lectern and takes it off

**Comment by Ynaught** [comment] 2024-06-22 00:29
But in combination with your mod, if Librarians Balance could detect the presence of your mod, would that "later tick" even be needed/could it be conditional based if your mod is present or not. If it's not present, then the "take off book" works, and if it doesn't detect it, the "take off book" feature just be disabled?

I assume both mods and datapacks can create NBT data. My concern is what happens if a mod that created an NBT tag (now called "components" btw, and yes, I hate it too) is removed? If that NBT data is used to identify the existence of the mod, then there needs to be a way to clear the data upon removal of the mod for safety. Maybe a tag that updates on every interaction. A system where both mods have a way of saying "I was here" and "I am still here". The "I am still here" check would be so that the other mod could remove the disabled mods remnant nbt data if it fails the re-confirmation. The issue would then be tick priority. Since both mods act on the same gametick. . . thats when it becomes a bit. . . messy I presume.

Would both mods creating an NBT data on one tick, and then delay by 1 tick to check for the other NBT data which was created the previous tick by both mods, would that help with the tick-priority? I am making alot of assumptions here. So forgive me on that front. (Also I edited my last comment, so sorry for that as well).

**Comment by Ramixin** [comment] 2024-06-22 00:35
that's the issue with attempted compatibility between data-packs and mods. Realistically, it would be best if the data-pack was a mod since it would allow me or @mistrk7 to easily detect it in the moment. Using NBT is the best I can do without creating a scuffed system.

**Comment by Ynaught** [comment] 2024-06-22 05:20
What about a synchronized scoreboard? One that updates on a timer and whose output is relative to world-time. As an example, scoreboard values could be "Tome Reader says this world has been active for 37 days". If it's the 38th day and this doesn't update, it means tomb reader isn't in the game to update the scoreboard, and thus the datapack could infer that the mod has been removed.

Alternatively, each mod could have a custom command to clear NBT data manually set by the others mod/datapack? Like, this is annoying, but I don't think mistrk7 knows how to mod. So I find this to be a fun little challenge to figure out how to force 2 incompatible systems communicate with eachother. It honestly sounds like a fun hackweek challenge (you know, sorta like a gamejam or those hack-off/ai vs events).

**Comment by mistrk7** [comment] 2024-06-22 08:55
@Ynaught You assume that the mod needs to be there for custom data to exist, but "minecraft:custom_data" components are vanilla, invisible and stay persistent on the item. I've already made a working datapack version that works with tome reader for you to download (check the librarian's balance issue). I wanted a way to detect the mod just to enable the patches on my end automatically.

That being said RamGemes suggested we can use the same system backwards too. 

@RamGemes You should add to the custom_data component when the enchanted book is placed. It can be something simple like 'tome: true'. I can detect that and then enable the changes 👍

**Comment by Ynaught** [comment] 2024-06-22 12:48
Yeah, sorry, I'm not well versed, but I do like learning. 😅 

That being said, I was more-so worried about how that custom_data would effect either mod if the other mod was removed. I was referring to a fail-safe state for that scenario incase that wasn't clear. My fear was if data was still there after a mod was removed, it would lead to the other mod making false assumptions about the other mod still being installed, thus causing issues if there is a form of cross-reliance on the others functionality for the former to even work when it assumes the latter is installed.

**Comment by mistrk7** [comment] 2024-06-22 17:54
If Ram makes it so that his custom data persists as long as the book is on the lectern, then I can make it work on a per-case basis

**Comment by Ynaught** [comment] 2024-06-22 18:02
Not to hold you up, I just like learning, but walk me through this. We have both mods installed. We place a book on a lectern, we uninstall Tome Reader, we go back to the lectern to remove the book using your datapack, it still has the old tome reader data despite the tome reader mod no longer being installed. . . wouldn't that imply you are meant to use Tome Readers GUI to remove the book even if the tome reader mod isn't there??? Wouldn't the GUI be non-functional without the mod? I'm just confused on how this would play out is all. Cause I assume the change you made on your end means when both mods are installed you take the book off the lectern via the tome reader GUI rather than just right clicking, ya? Cause right clicking is how you gain access to the gui, which is the whole point of the tome reader mod.

**Comment by mistrk7** [comment] 2024-06-22 18:08
Yep so in that case you would just break the lectern to get rid of it. I can detect if the book still has tome's data and remove it before it gets placed.

**Comment by Ynaught** [comment] 2024-06-22 19:21
Fair enough trade-off I suppose.

**Comment by Ramixin** [comment] 2024-06-24 18:35
I will be applying the `TomeReader` tag to the lectern rather than to the book since that still uses NBT rather than components

**Comment by Ynaught** [comment] 2024-06-24 18:50
I agree with this since, ever since the version you sent me @mistrk7 it created a new component/nbt data on the book after taking them off the lecturn. Idk if there is another mod that allows me to do this or if it's vanilla but if I have 2 books/tomes with the exact same enchantments on them, I can stack them in my inventory/use the same inventory slot. That is, I can so long as they don't have differing nbt tags. By placing the NBT on the lectern rather than the books, this would avoid that edge-case issue entirely.

**Comment by mistrk7** [comment] 2024-06-24 19:44
> I will be applying the `TomeReader` tag to the lectern rather than to the book since that still uses NBT rather than components

Sounds good

**Comment by Ramixin** [comment] 2024-06-24 20:11
@mistrk7 would it be sufficient enough for the mod to check for `custom_data` component, or should the mod also be able to check for a specific NBT tag?

**Comment by mistrk7** [comment] 2024-06-24 21:06
> @mistrk7 would it be sufficient enough for the mod to check for `custom_data` component, or should the mod also be able to check for a specific NBT tag?

It should specifically check for "sealed: 1b" in the custom_data component.

**Comment by Ramixin** [comment] 2024-06-25 00:46
![2024-06-24_20 43 31](https://github.com/RamGemes/Tome-Reader/assets/104311709/246b6131-a881-4792-8902-c0db880ba0a3)
Here is the book closes. If this is good, I will close the issue, push the commit, and publish the update

**Comment by mistrk7** [comment] 2024-06-25 10:00
> Here is the book closes. If this is good, I will close the issue, push the commit, and publish the update

@RamGemes It looks great! further discussion should move to the report on my repo. 

https://github.com/mistrk7/librarians-balance/issues/8

**Closed as completed** 2024-06-25 21:21 UTC
